const API_URL = process.env.NEXT_PUBLIC_API_URL || "http://localhost:8000";

export async function triggerTamperAttack(vehicleId: string): Promise<any> {
  // Fetch tampered firmware from Next.js public folder
  const formData = new FormData();
  const res = await fetch("/demo/firmware_tampered.bin");
  if (!res.ok) throw new Error("Could not load tampered firmware binary.");
  const blob = await res.blob();
  formData.append("firmware", blob, "firmware_tampered.bin");

  // Fetch signed metadata (generated by the backend /sign endpoint)
  const metaRes = await fetch("/demo/signed_metadata.json");
  if (!metaRes.ok) throw new Error("Could not load signed metadata.");
  const meta = await metaRes.json();

  formData.append("signature", meta.signature);
  formData.append("public_key", meta.public_key);
  formData.append("trusted_merkle", JSON.stringify({
    root: meta.merkle_root,
    leaves: meta.merkle_leaves,
  }));
  formData.append("signed_at", meta.signed_at || "");
  formData.append("firmware_hash_signed", meta.firmware_hash || "");

  const verifyRes = await fetch(`${API_URL}/verify`, { method: "POST", body: formData });
  const verifyData = await verifyRes.json();

  // Log alert to Firestore via ledger API if tampered
  if (!verifyData.installation_safe) {
    await fetch(`${API_URL}/ledger/update`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        vehicle_id: vehicleId,
        version: "TAMPERED",
        firmware_hash: "tampered_detected",
      }),
    });
  }
  return verifyData;
}

export async function triggerRollbackAttack(vehicleId: string): Promise<any> {
  const res = await fetch(`${API_URL}/ledger/update`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      vehicle_id: vehicleId,
      version: "1.0.0",
      firmware_hash: "rollback_test_hash",
    }),
  });
  const data = await res.json();
  return { status: res.status, ...data };
}

export async function getFleet(): Promise<any> {
  const res = await fetch(`${API_URL}/fleet`);
  return res.json();
}
